config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs do 
      get 'assign_developer', on: :member
    end
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


 
  root 'home#index'
  get 'bugs/assign_developer'
  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/edit'
  get 'users/destroy'
  get 'users/show'
  get 'users/index'
  #devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   # resources :bugs
#  devise_for :users
  #root 'projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
	
	belongs_to :manager, :class_name => "User"
	has_one :project_name, :class_name => "ProjectUser", :foreign_key => "project_id", dependent: :destroy
	has_many :bugs, foreign_key: :project_id, dependent: :destroy
	
	def self.current
    	Thread.current[:project]
  	end

  	def self.current=(project)
    	Thread.current[:project] = project
  	end

  	def self.project_manager(project, id)
  		project.where(manager_id: id)
  	end


  	def self.project_name(curr_user_id)
  		Project.where(id: ProjectUser.select(:project_id).where(user_id: curr_user_id))
  	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]
  def new
    @project = Project.new
    @project_user = ProjectUser.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.manager_id = current_user.id
    authorize @project
    if current_user.user_types != "manager"
      flash[:error] = "Only managers can create projects!"
      render 'new'
    elsif Project.find_by_name(@project.name) != nil
      flash[:error] = "A project with the same name already exists!"
      render 'new'
    elsif @project.save!
      flash[:success] = "Project was successfully created!"
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    
    @project = Project.find(params[:id])
    authorize @project
    if Project.where.not(id: @project.id).find_by_name(@project.name).present?
      flash[:error] = "A project with the same name already exists!"
      render 'edit'
    elsif @project.update_attributes!(project_params)
      if !params[:project_user_attributes].nil?
        params[:project_user_attributes][:user_id].each do |user_id|
          @project_user = ProjectUser.new(project_user_params)
          @project_user.project_id = @project.id
          @project_user.user_id = user_id
          @project_user.save!
        end
      end
      flash[:success] = "Project successfully updated!"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
    session[:project_id] = @project.id
  end

  def index
    @projects = Project.all
    authorize @projects
  end

  def destroy

    @project = Project.find(params[:id])
    authorize @project
    puts "Deleting project " + @project.id.to_s
    @project.destroy
    redirect_to action: 'index'
  end
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :manager_id, project_user_attributes: [:project_id, :user_id]) 
  end

  private
  def project_user_params
      params.require(:project_user_attributes).permit(:project_id, :user_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/create.html.erb
<h1>project#create</h1>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @project, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
			<%= render 'shared/error_messages' %>
			<div class="field"> <br />
				<%= f.label :name %>
				<%= f.text_field :name, autofocus: true %>
			<div>
				<br>	
			<%= f.label :Developers %><br>
    	  	<%= select_tag "project_user_attributes[user_id]", options_from_collection_for_select(User.developers_not_assigned_to_project(Project.all), "id", "name"), multiple: true, :style => "width: 500px; height: 100px;" %>
    	  <br /><br />
    	  		<%= f.label :Qas %><br>
    	      	  	<%= select_tag "project_user_attributes[user_id]", options_from_collection_for_select(User.qas_not_assigned_to_project(Project.all), "id", "name"), multiple: true, :style => "width: 500px; height: 100px;" %>
    	  <br /><br />
			<%= f.submit "Update", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/projects/index.html.erb
<%#= link_to "Create Project", controller:"projects", action: "new" if policy(Project).new? %>
<%#= link_to "Create Project", new_project_path, class: 'btn btn-primary' if policy(Project).new? %>
<br>
<% if current_user.user_types == "manager" %>
	<% if Project.project_manager(@projects, current_user.id).empty? %>
		<p> There are no projects under this manager </p>
	<% else %>
		<h1 class = "text-center">Projects under your supervision</h1>
		
		<table class = "table responsive">
				<thead class= "table-info">
					<tr>
						<th class = "text-center"><strong>Name</strong></th>
						<th class = "text-center">View</th>
					</tr>
				</thead>
				<tbody>
				<% Project.project_manager(@projects, current_user.id).each do |project| %>
					<tr>
						<td class = "text-center"><strong><%= project.name %></strong></td>
						<td class = "text-center"><%= link_to "Show", project, class: 'btn btn-primary'%></td>
					</tr>
					<% end %>
				</tbody>
		</table>



	<% end %>


<% else %>
	<% if Project.project_name(current_user.id).empty? %>
		<p>You are not selected for any project</p>
	<% else %>
	<h1 class = "text-center">Projects</h1>
	<table class = "table responsive">
				<thead class= "table-info">
					<tr>
						<th class = "text-center"><strong>Name</strong></th>
						<th class = "text-center">View</th>
					</tr>
				</thead>
				<tbody>
		<% Project.project_name(current_user.id).each do |project|%>
			<tr>
				<td class = "text-center"><strong><%= project.name %></strong></td>
				<td class = "text-center"><%= link_to "Show", project, class: 'btn btn-primary'%></td>
			</tr>
		<% end %>
			<% end %>
		</tbody>
	</table>	
<% end %>

<br> <br>
<div class = "text-center">
<%= link_to "Back", root_path, class: 'btn btn-lg btn-primary'%></div>

app/views/projects/new.html.erb
<% provide(:title, 'Create Project') %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @project, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
			<%= render 'shared/error_messages' %>
			<div class="field"> <br />
				<%= f.label :name %>
				<%= f.text_field :name, autofocus: true %>
			</div>
			<br>
			<%= f.submit "Create Project", class: "btn btn-primary"%>
		<% end %>
	</div>
</div>

app/views/projects/show.html.erb
<%= link_to "Create Bug", new_project_bug_path(@project), class: "btn btn-warning"%>
<%= link_to "Add Users", edit_project_path(@project), class: "btn btn-info" if policy(@project).is_user_manager?%>
<%= link_to "Destroy", project_path(@project), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" if policy(@project).destroy?%>
<%= link_to "Back", projects_path, class: "btn btn-primary"%>


<h1 class = "text-center">Project Info</h1>
<table class = "table responsive">
	<thead class= "table-info">
		<tr>
			<th>Project Name</th>
			<th>Manager</th>
			<th>Developers</th>
			<th>Qas</th>
			<th>Bugs</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @project.name %></td>
			<td><% User.select(:name).where(id: @project.manager_id).each do |manager| %>
				<%= manager.name %>
				<% end %>
			</td>

			<td>
				<% if User.developers_assigned_to_current_project(@project.id).empty? %>
				<p>No developers assigned</p>
				<% else %>
				<% User.developers_assigned_to_current_project(@project.id).each do |developer| %>
				<li> <%= developer.name %> </li>
				<% end %>
			<% end %>
			</td>


			<td>
				<% if User.qas_assigned_to_current_project(@project.id).empty? %>
				<p>No QA assigned</p>
				<% else %>
				<% User.qas_assigned_to_current_project(@project.id).each do |developer| %>
				<li> <%= developer.name %> </li>
				<% end %>
			<% end %>
			</td>

			<td>
				<%= link_to "Show", project_bugs_path(@project), class: 'btn btn-xs btn-primary' %>
			</td>
		</tr>
	</tbody>
</table>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>