config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs do 
      get 'assign_developer', on: :member
    end
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


 
  root 'home#index'
  get 'bugs/assign_developer'
  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/edit'
  get 'users/destroy'
  get 'users/show'
  get 'users/index'
  #devise_for :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   # resources :bugs
#  devise_for :users
  #root 'projects#index'
end

app/models/bug.rb
class Bug < ApplicationRecord

  enum bug_statuses: [ :status_new, :status_started, :status_resolved ]
  enum feature_statuses: [ :new_status, :started_status, :completed_status]
  validates :title, uniqueness: true, presence: true
  validates :category, presence: true
  
  mount_uploader :screenshot, ImageUploader

  belongs_to :project
  belongs_to :user, optional: true


  def self.current
    Thread.current[:bug]
  end

  def self.current=(bug)
    Thread.current[:bug] = bug
  end

  def assigned?
    developer_id.present?
  end

  def is_feature?
    category == 'feature'
  end

  def is_bug?
    category == 'bug'
  end

  def resolved?
    statuses == 'Resolved' || statuses == 'Completed'
  end

  def self.find_bug_creator(bug)
    User.select(:name).where(id: bug.created_by)
  end
 
  def self.find_bug_developer(bug)
    User.select(:name).where(id: bug.developer_id)
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_project

  def index
    @bugs = @project.bugs
    authorize @bugs
  end

  def new
    @bug = Bug.new
  end

  def create
    @bug = Bug.new(bug_params)
    @bug.project_id = session[:project_id]
    @bug.created_by = current_user.id
    
    if @bug.title.empty?
      flash[:error] = "Title field cannot be empty!"
      render 'new'
    elsif Bug.where(title: @bug.title).empty? == false
      flash[:error] = "A bug with the same name already exists!"
      render 'new'
    elsif @bug.save!
      flash[:success] = "Bug was successfully created!"
      redirect_to  project_bug_path(@project,@bug)
    else
      render 'new'
    end
  end

  def show
    @bug = Bug.find(params[:id]) 
    authorize @bug
  end

  def edit
    @bug = Bug.find(params[:id])

  end

  def update
    @bug = Bug.find(params[:id])
    authorize @bug
    if @bug.title.empty?
      flash[:error] = "Title field cannot be empty!"
      render 'edit'
    elsif Bug.where.not(id: @bug.id).where(title: @bug.title).present?
      flash[:error] = "A bug with the same name already exists!"
      render 'edit'
    elsif @bug.update_attributes!(bug_params)
      flash[:success] = "Bug successfully updated!"
      redirect_to  project_bug_path(@project,@bug)
    else
      render 'edit'
    end
  end

  def destroy
    #@bug = Bug.find(params[:id])
    @bug = Bug.find(params[:id])
    puts "Deleting bug " + @bug.id.to_s
    @bug.destroy

    flash[:success] = "Bug successfully deleted!"
    redirect_to controller: "bugs", action: 'index'


    #Bug.find(params[:id]).destroy
    #flash[:success] = "Bug successfully deleted!"
    #redirect_to controller: "projects", action: "show", id: session[:project_id]
  end

  def assign_developer
    @bug = Bug.find(params[:id])
    authorize @bug
    if current_user.user_types == "developer"
      @bug.update_attribute(:developer_id, current_user.id)
      flash[:success] = "Bug assigned to the developer!"
    else
      flash[:error] = "Only developers can be assigned to solve bugs!"
    end
    redirect_to  project_bug_path(@project,@bug)
  end

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id].to_i)
  end
  
  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :screenshot, :category, :bug_status, :feature_status)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/create.html.erb
<h1>Bugs#create</h1>
<p>Find me in app/views/bugs/create.html.erb</p>

app/views/bugs/destroy.html.erb
<h1>Bugs#destroy</h1>
<p>Find me in app/views/bugs/destroy.html.erb</p>

app/views/bugs/edit.html.erb
<%= javascript_include_tag "bugs", "data-turbolinks-track" => true  %>
<% provide(:title, 'Create Bug') %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @bug, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
			<%= render 'shared/error_messages' %>
			
			<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title, autofocus: true %>
			</div>

			<div class="field"> 
				<%= f.label :description %><br>
				<%= f.text_area :description, cols: "20", rows: "5" %>
			</div>

			<div class="field"> 
				<%= f.label :deadline %>
				<%= f.datetime_select :deadline %>
			</div>

						

		
            <div class="field"> <br />
                <%= f.radio_button :category, 'true', onClick: "evaluateType(this)" %>
                <%= label :category, 'Bug' %>
                <%= f.radio_button :category, 'false', onClick: "evaluateType(this)" %>
                <%= label :category, 'Feature' %>
            </div>
            <div class="field" id="bugs_status"><br />
                <%= f.label "Status" %>
                <%= f.select :bug_status, Bug.bug_statuses.map { |key, value| [key.humanize.split(' ').second.capitalize, value] }%> 
            </div>  
            <div class="field" id="feature_status"><br />
                <%= f.label "Status" %>
                <%= f.select :feature_status, Bug.feature_statuses.map { |key, value| [key.humanize.split(' ').first.capitalize, value] } %>
            </div>

		  	<br>
		  	<div class="field">
		  		<%= f.label :screenshot %><br>
    			<%= f.file_field :screenshot, onchange: "validateFiles()" %>
		  	</div>
		  	<br>
		  	<br>

			<%= f.submit "Update", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>




<% content_for :javascript_includes do %>
  <%= javascript_include_tag "bugs.js" %>
<% end %>

app/views/bugs/index.html.erb
<h1 class = "text-center">All Bugs of this Project</h1>
<table class = "table responsive">
	<thead class= "table-info">
		<tr>
			<th class="text-center">Title</th>
			<th class="text-center">Type</th>
			<th class="text-center">Status</th>
			<th class="text-center">Screenshot</th>
			<th class="text-center">Details</th>
		</tr>
	</thead>



	<% @bugs.each do |bug| %>
		<tr>
			<td class="text-center"><%= bug.title %></td>
			<% if bug.category == "true" %>
				<td class="text-center"><%= "Bug" %></td>
				<% if bug.bug_status == 0 %>
					<td class="text-center"><%= "new" %></td>				
				<% elsif bug.bug_status == 1 %>
					<td class="text-center"><%= "started" %></td>
				<% elsif bug.bug_status == 2 %>
					<td class="text-center"><%= "resolved" %></td>
				<% end -%>
			<% elsif bug.category == "false" %>
				<td class="text-center"><%= "Feature" %></td>
				<% if bug.feature_status == 0 %>
					<td class="text-center"><%= "new" %></td>				
				<% elsif bug.feature_status == 1 %>
					<td class="text-center"><%= "started" %></td>
				<% elsif bug.feature_status == 2 %>
					<td class="text-center"><%= "completed" %></td>				
				<% end -%>
			<% end %>			
			<td><%= image_tag(bug.screenshot.url, alt: 'Image', :class => "screenshot") if bug.screenshot? %></td>
			<td class="text-center"><%= link_to "Show", {controller: "bugs", action: "show", id: bug.id}, class: 'btn btn-xs btn-primary' %></td>
		</tr>
	<% end %>
</table>
<br><br>
<div class = "text-center">
<%= link_to "Back", project_path(@project), class: 'btn btn-lg btn-primary'%></div>

app/views/bugs/new.html.erb
<%= javascript_include_tag "bugs", "data-turbolinks-track" => true  %>

<% provide(:title, 'Create Bug') %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @bug, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
			<%= render 'shared/error_messages' %>
			
			<div class="field">
				<%= f.label :title %><br>
				<%= f.text_field :title, autofocus: true %>
			</div>
			<br>
			<div class="field"> 
				<%= f.label :description %><br>
				<%= f.text_area :description, cols: "20", rows: "4" %>
			</div>
			<div class="field">
				<%= f.label :deadline %><br>
				<%= f.datetime_select :deadline %>
			</div>
			<br>
		
			
			<div class="field"> <br />
                <%= f.radio_button :category, "true", :checked => true, onClick: "evaluateType(this)" %> Bug
                <%= f.radio_button :category, "false", onClick: "evaluateType(this)" %> Feature
            </div>

		
	  		<div class="field" id="bugs_status"><br />
                <%= f.label "Status" %>
                <%= f.select :bug_status, Bug.bug_statuses.map { |key, value| [key.humanize.split(' ').second.capitalize, value] } %>
            </div> 
            <div class="field" id="feature_status" style="display: none;"><br />
                <%= f.label "Status" %>
                <%= f.select :feature_status, Bug.feature_statuses.map { |key, value| [key.humanize.split(' ').first.capitalize, value] } %>
            </div>
		  	
		  	


		  	<div class="field">
		  		<%= f.label :screenshot %><br>
    			<%= f.file_field :screenshot, onchange: "validateFiles(this);" %>
		  	</div>
		  	<br>

			<%= f.submit "Create Bug", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/bugs/show.html.erb
<hr>
<h1 class="text-center">Bug Info</h1>
<hr>
<div><strong>Bug Title:- </strong><%= @bug.title %></div>


<% Bug.find_bug_creator(@bug).each do |creator| %>
	<h5><strong>Bug_Creator_name:- </strong><%= creator.name %></h5>	
<% end -%>





<% if @bug.developer_id.nil? %>
	<span><strong>No developer assigned</strong></span><br>	
	<%= link_to "Assign me as developer", action: "assign_developer", id: @bug%>
<% else %>
	<% Bug.find_bug_developer(@bug).each do |developer| %>
		<div><strong>Developer Assigned:- </strong><%= developer.name %></div>
	<% end 	%>

<% end %>
<br>

 <span><strong>Deadline:</strong></span>
 <span><%= @bug.deadline.to_date.strftime("%d-%m-%Y") %></span>
 <br>


<h2 class="text-center">Bug ScreenShoot</h2>

<%= image_tag(@bug.screenshot.url, alt: 'Image', :size => "740x640", class: "img-responsive center-block") if @bug.screenshot? %>
	
<br><br>
<%= link_to "Edit", edit_project_bug_path, class: "btn btn-primary" %>  
<%= link_to "Destroy", project_bug_path(@project,@bug), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger'%>
<%= link_to "Back", project_bugs_path, class: "btn btn-primary"%>

app/views/bugs/update.html.erb
<h1>Bugs#update</h1>
<p>Find me in app/views/bugs/update.html.erb</p>